# Generated by Django 3.0.6 on 2020-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.IntegerField(max_length=100),
        ),
    ]
